// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vdiqihlidfnjbednpbtx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZkaXFpaGxpZGZuamJlZG5wYnR4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY3NDM3MzcsImV4cCI6MjA3MjMxOTczN30.TD_BbrPPw4K0HcdhLMvBz21Fj0NtJ4KBg3o7kGQeeKw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});